### ISSUE TITLE
RestaurantsPage console error

### ISSUE THREAD

**Issue by esther615kim** [react-node-project/butler-client#45]
@bereal1995 
could you please check? thanks
![image](https://user-images.githubusercontent.com/75744588/150678379-acfdb407-95e6-4211-b33c-b2d5ed4a1a3a.png)

**Comment by bereal1995** [comment]
url에 쿼리스트링이 없어서 그런데 추가부탁드려요 없을때는 홈으로 리다이렉션하도록 수정했습니다.

ex) http://localhost:3000/restaurants?latitude=53.4083714&longitude=-2.9915726
