### ISSUE TITLE
[MSW] 18:45:13 GET http://localhost:4000/api/v1/getstores (403 Forbidden)

### ISSUE THREAD

**Issue by esther615kim** [react-node-project/butler-client#50]
![image](https://user-images.githubusercontent.com/75744588/152675456-2db0daa9-e943-476b-a6bd-83e35015e83c.png)

@bereal1995 
CategorySlicer를 랜딩 페이지 중간에 넣어봤는데 안나오네요
지금 제 로컬에서는 restaurants 페이지는 문제없는데요. 혹시 제가 빼먹은 설정이 있으면 알려주시면 감사요

https://github.com/react-node-project/butler-client/blob/landing/src/pages/Home.jsx

**Comment by lucid-jin** [comment]
filter 타입아이디를 안넣워주면 에러 나는건데 제 생각에 default 를 delivery 기준으로 바꾸면 사용시편하지 않을까싶어요

**Comment by bereal1995** [comment]
지금 API 불러오는 방식인데 상수값으로 넣기로해서 
제가 작업 끝나면 말씀드릴게요-
